# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r Loading and preprocessing the data, echo=TRUE}
setwd("./activity")
activity <- read.csv("activity.csv")
dailySteps <- tapply(activity$steps, activity$date, sum)
hist(dailySteps, main="Number of Steps by Day", xlab="Steps")
```


## What is mean total number of steps taken per day?
```{r What is mean total number of steps taken per day?, echo=TRUE}
meanSteps <- mean(dailySteps, na.rm=TRUE)
meanSteps # 10766.19
medianSteps <- median(dailySteps, na.rm=TRUE)
medianSteps #  10765
```

## What is the average daily activity pattern?
```{r What is the average daily activity pattern?, echo=TRUE}
adap = tapply(activity$steps, activity$interval, mean, na.rm=TRUE)
adap # Raw Data
plot(adap, type="l", xlab="5 Minute Interval", ylab="Average Number of Steps (not counting NA)")   # Line Plot

g <- data.frame(adap, names(adap))
names(g) <- c("activity", "interval")
as.numeric(as.character(g[g$activity==max(g$activity),2][1])) # Interval 835 has the maximum average number of steps 206.1698
```

## Imputing missing values
```{r Imputing missing values, echo=TRUE}
activityNA = is.na(activity$steps)
sum(activityNA) # 1. 2304 missing values
# 2. replace the NA with the mean of non NA values for that 5 minute period
activityImputed = activity
adapInterval = as.numeric(names(adap))
adapImputedSteps = as.numeric(adap)
imp_table = data.frame(adapInterval, adapImputedSteps)
for (i in 1:nrow(activity)) { #3. Create a new dataset with imputed values 
  if (activityNA[i]) {
    activityImputed$steps[i] = imp_table[imp_table$adapInterval == activityImputed$interval[i], 2]
  }
}
activityImputedDaily <- tapply(activityImputed$steps, activityImputed$date, sum)
hist(activityImputedDaily, main="Number of Steps by Day with NA replaced by Imputed Values", xlab="Steps") #4. 
mean(activityImputedDaily)   #4. Mean steps per day:   10766.19
median(activityImputedDaily) #4. Median steps per day: 10766.19
```	

## Are there differences in activity patterns between weekdays and weekends?
```{r Are there differences in activity patterns between weekdays and weekends?, echo=TRUE}
newdate <- strptime(activityImputed$date, "%m/%d/%Y")
wdays <- weekdays(newdate)
wend  <- ifelse(wdays == 'Saturday' | wdays == 'Sunday', 1, 0)
activityImputed <- data.frame(activityImputed, wdays, wend)

actImp <- with(activityImputed, tapply(steps, list(interval, wend),mean))
steps <- c(actImp[,1], actImp[,2])
intervals <- names(adap)
df <- data.frame(rep(intervals, 2), steps, rep(c("weekday", "weekend"), each=288)) #1. Create a new factor variable in the dataset with two levels "weekday" and "weekend"
names(df) <- c("intervals", "steps", "days")

#2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).
library(lattice)
xyplot(steps ~ intervals | days, data=df, t="l", xlim=c(-10,300), ylab="Number of steps", xlab="Interval", scales=list(x=list(at=c(0,60,120,180,240),labels=c(0,500,1000,1500,2000))) )
```